### ISSUE TITLE
Discount Description/Label displays in checkout when it should not

### ISSUE THREAD

**Issue by friendscottn** [subscribepro/subscribepro-magento2-ext#155]
With the new Magento 2.4.5 updates to this module that require you to create a cart rule we're noticing that the cart rule displays when it should not. 

Steps to Reproduce
- Magento 2.4.5, Subscribe Pro module 1.5.16
- Setup the rule as specified [here](https://docs.subscribepro.com/integrations/magento-2/installation/step-6-configure-subscription-discount/) making sure to include a label (Subscription)
- Setup another 10% off coupon and add a label for that (10% Off)
- On the frontend add a non-subscription item to the cart and apply the 10% coupon

Expected Result:
- You should only see the 10% off coupon description

Actual Result: 
- You see both the 10% off coupon description and the subscribe pro coupon description

Our Solution:
- Remove the Label and Description from the subscribe pro cart rule
- Make sure to set the "Priority" field very high so that Subscribe Pro gets that last word among cart rules. I set mine to 1000
- Add the following change to reintroduce the original subscribe pro discount text in vendor/subscribepro/subscribepro-magento2-ext/Model/Quote/ItemSubscriptionDiscount.php:

Replace this:
```php
    protected function addDiscountDescription(QuoteItem $item)
    {
        $discountDescriptions = $item->getAddress()->getDiscountDescriptionArray();
        $item->getAddress()->setDiscountDescriptionArray($discountDescriptions);
    }
```

With this:
```php
    protected function addDiscountDescription(QuoteItem $item)
    {
        $discountDescriptions = $item->getAddress()->getDiscountDescriptionArray();
        // BEGIN MOD: Fix discount description on checkout
        $discountDescriptions[self::KEY_DISCOUNT_DESCRIPTION] = __('Subscription');
        // END MOD
        $item->getAddress()->setDiscountDescriptionArray($discountDescriptions);
    }
```

**Comment by czettnersandor** [comment]
After some testing, we found this can be solved by adding the following action condition to the rule:
- scroll down and open the "Actions" accordion on the cart rule edit page
- in "Apply the rule only to cart items matching the following conditions (leave blank for all items).", click +, then choose "Subscription - Status", then "Part of Subscription (New or Re-order)"

![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/263174/786581e3-e24e-4d03-a933-82650e428c14)

This will make the cart rule only applicable for items that are subscription based. Otherwise, you can set up the rules as desired.  For example, when the cart rule with a coupon is applied, and it discards subsequent rules, and has a higher priority than the subscription discount, the subscription discount is not applied as expected.

**Comment by friendscottn** [comment]
That sounds like a decent fix to me.
