### ISSUE TITLE
Allow option to display Expired cards in admin checkout/frontend checkout

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-ext#163]
PRs: [#242](https://github.com/subscribepro/subscribepro-magento2-ext/pull/242)

Currently Expired cards are not visible in checkout if they are expired.  Is it possible to give the merchant the choice to display expired credit cards?

We should do exploration, try to understand the root cause before proceeding with any solution.

**Comment by garthbrantley** [comment]
@eugene-shab Now that we have changed the iframe implementation, please report back whether expired credit cards are visible in each of these 3 places:

- Checkout, Logged in customer
- Customer wallet page
- Admin cart

**Comment by eugene-shab** [comment]
@garthbrantley I have made an investigate on expired cards. I don't think that our new iframe affects on the availability of cards. 

It only validates that new cards are not expired. All cards that the customer already has, can be displayed on the account/checkout/admin pages. But an error occurs when you try to pay with such a card.

Since I do not pass validation when trying to save an expired card, but when displaying a card on the site, data from the vault_payment_token table is used, from which expired cards are retrieved without any problems


Also, when researching the problem of an expired card, I found that if you change the card expiration date in the vault_payment_token table, and then save the profile in Magento, an attempt is made to save the new date(10/2022) in the platform.

The platform gives an error that the data is incorrect, but still partially saves the data.

After this, duplicate card data appears on the platform. The platform profile indicates that the card is expired.

But if you try to go through a checkout with this card, it will pass. A card with an old date(12/2025) that is valid will be used in the platform.
![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1384207/3c111167-7a97-48e3-b2ef-3e08d3ffc0b2)
![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1384207/fb398119-64a8-4821-a9bf-78df133a80ac)
![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1384207/87b3a865-fcef-479f-9ebb-3b88d5e3235a)

**Comment by garthbrantley** [comment]
@chrismshea - Based on what @eugene-shab says, this seems incorrect, can you please shown an example?

> Currently Expired cards are not visible in checkout if they are expired. Is it possible to give the merchant the choice to display expired credit cards?

**Comment by garthbrantley** [comment]
@chrismshea Can you validate this please?

**Comment by chrismshea** [comment]
@garthbrantley validated

1. In Magento 2 login as a customer
2. Navigate to My Account > Stored Payment Methods
3. Click the button to create a new card
4. Connect to the Magento 2 database and identify the last record created in the `vault_payment_token` table
5. Update the latest record in the `vault_payment_token` table to have a value for `expires_at` in the past.
```
update vault_payment_token set expires_at = '2023-01-01 00:00:00' where gateway_token = '7685454';
```
6. In Magento 2 refresh the My Account > Stored Payment Methods page.  Observe your payment method is now not shown.
