### ISSUE TITLE
Order Callback | Unable to create order when payment method 'checkmo'

### ISSUE THREAD

**Issue by chrismshea** [subscribepro/subscribepro-magento2-ext#192]
PRs: [#238](https://github.com/subscribepro/subscribepro-magento2-ext/pull/238)

M2 order callback mechanism must support recurring orders from Subscribe Pro which include offline payment method.

Chris shows in the video where `paymentMethodCode` will show up in the order callback message when configured in this scenario.

![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/8466130/001ef15f-586a-4b06-8cf7-bb024caca316)

## Report from Chris

When attempting to place a recurring order using the `Magento 2 - Subscribe Pro Order Callback` connection type and using `checkmo` as the payment method the order fails with the attached exception.

[exception.log](https://github.com/subscribepro/subscribepro-magento2-ext/files/12454393/exception.log)

https://www.loom.com/share/00589060e21e4959b798a6fc1bfb6857?sid=ce7bee91-3f75-497b-a5ae-257a61285c1e

**Comment by eugene-shab** [comment]
@chrismshea Is it possible to clarify in more detail the problem for which it is necessary to remove the `Use Default` to avoid an incident?

**Comment by eugene-shab** [comment]
@garthbrantley At the moment, I see that Magento does not see the difference in order callback requests for online and offline payments.

When making online payments, the platform sends data about the card and the profile that was created for the card

```
"payment": {
    "paymentToken": "PYxAAiV0AM9MzA8qlsswfpSRAhB",
    "paymentProfileId": 7803297,
    "paymentProfileType": "spreedly_vault",
    "paymentMethodType": "credit_card",
    "creditcardType": "visa",
    "creditcardLastDigits": "1111",
    "creditcardMonth": "11",
    "creditcardYear": "2025"
  },
```

When making an offline payment(like `checkmo`), Magento receives only the `paymentMethodCode`

```
  "payment": {
    "paymentMethodCode": "checkmo"
  },
```

If we'll check the payment type only by the existing of paymentMethodCode, I am not sure of the reliability of this scheme.

Is it possible to transfer the payment type - offline/online so that the type can be added to the condition?
