### ISSUE TITLE
No error message when 3DS2 authentication fails

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#220]
PRs: #228

Error message should be displayed to customers in all 3DS2 failure scenarios.

## Scenario 1: 3DS2 Merchant Profile not configured in Commerce Platform

![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/8466130/55e05f20-aeae-4d8d-aad8-9b82876ee3a2)

## Scenario 2: Non-3DS2 test card used

Use test card '4111111111111111` and checkout.

Enabled 3DS2 on M2 extension:

![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/8466130/2493bc5b-e7fb-4229-a0bb-37041f6b0b7e)

## Scenario 3: 3DS2 test card which simulates authentication failure used 

Use test card: `2303779999000291 `

5 | Payment authentication request that results in a not-authenticated frictionless authentication | PA | N | 2303779999000291
-- | -- | -- | -- | --

**Comment by eugene-shab** [comment]
@garthbrantley Is it okey using message '`Transaction has been declined. Please try again later.`' for all 3 scenarios? Because I only get the error message body in the second scenario, and even there it is not entirely clear to the client and does not reflect the essence of the problem

Scenario - 2
errorDescription: "No matching card range data"
errorDetail: "No EMV 3DS card ranges match submitted request"

**Comment by garthbrantley** [comment]
> @garthbrantley Is it okey using message '`Transaction has been declined. Please try again later.`' for all 3 scenarios? Because I only get the error message body in the second scenario, and even there it is not entirely clear to the client and does not reflect the essence of the problem
> 
> Scenario - 2 errorDescription: "No matching card range data" errorDetail: "No EMV 3DS card ranges match submitted request"

Yes, agree.
