### ISSUE TITLE
Fix Admin Panel Cart / Checkout with PaymentFields

### ISSUE THREAD

**Issue by garthbrantley** [subscribepro/subscribepro-magento2-ext#241]
PRs: [#214](https://github.com/subscribepro/subscribepro-magento2-ext/pull/214)

Issues:

- [x] I can't get this to work at all with Config 1.
- [x] I don't see a token being passed back to M2 server.
- [x] `api.subscribepro.com` should not be hard coded

**Comment by garthbrantley** [comment]
Issue occurs:

- Use Config 2 (probably happens w/ Config 1 also)
- Use existing customer, go to Edit Customer page
- Click "Create Order" button at top
  - ![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/8466130/7d60174f-31e9-4f82-b623-951537da47d7)
- Add a product
- Click Subscribe Pro new card payment method
- Set shipping method
- Add credit card, expiration date, cvv - `2303779999000275` card
- Click Submit Order
- See:

![Image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/8466130/192b2aaa-5377-4214-a926-1dac96624f2f)

**Comment by eugene-shab** [comment]
@garthbrantley I see a difference between Config2 and Config1 response from platform.
So, for Config2 there are no required fields: `creditcard_last_digits` , `creditcard_fist_digits`, `creditcard_month`, `creditcard_year`, `creditcard_type`
This is why the code throws an error because the required fields are missing.
![image](https://github.com/subscribepro/subscribepro-magento2-ext/assets/1384207/b02533a4-e534-4cab-b00b-1323a125ff18)

For the correct operation of the code, the fields must be in the response from Platforms for both configs. 

If you see another way please share it.

**Comment by eugene-shab** [comment]
@garthbrantley Waiting for new fields and will be tested.
