### ISSUE TITLE
Cart does not merge items on update

### ISSUE THREAD

**Issue by yrudiuk** [subscribepro/subscribepro-magento2-ext#73]
Hello,

We've noticed an issue with cart items merge, steps to reproduce:
1.) Add "one time purchase" product to cart
2.) Add the same product with subscription to cart
3.) In cart, remove subscription from last added product to it become "one time purchase" as well
As the result items haven't been merged, hence we have 2 different entries in quote.

Note: when adding "one time purchase" product several times to cart, merging works properly, so we assume this is not a magento bug.

Thank You

**Comment by imkingdavid** [comment]
Good morning,

Thank you for reporting this issue. We are currently investigating it and will let you know as we determine whether it is a Subscribe Pro issue and what our plans and timeline are for resolving it.

**Comment by imkingdavid** [comment]
Hello,

After reviewing this issue we have determined that the use case is very uncommon and the customer has the ability to work around it in the cart without too much trouble. Additionally, fixing this behavior would cause a significant amount of effort and run the risk of introducing new bugs. Lastly, because it would modify the behavior of the Magento cart, we feel it is beyond the scope of our extension to fix.

As a result, we have decided not to fix this issue.

Thank you!
